spring:
  application:
    name: gateway
  aop:
      proxy-target-class: true

server:
  port: ${PORT:8080}
  contextPath: /${spring.application.name}

security:
  user:
    password: password
  oauth2:
    client:
      accessTokenUri: http://localhost:8000/oauth-server/oauth/token
      userAuthorizationUri: http://localhost:8000/oauth-server/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:8000/oauth-server/user

zuul:
  routes:
    user:
      path: /oauth-server/user/**
      url: http://localhost:8000/oauth-server/user
    resource:
      path: /resource-server/**
      url: http://localhost:8010/resource-server

logging:
  file: ${user.home}/asg/logs/${spring.application.name}-${server.port}.log

debug: true